name: valorant_info
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.5
environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  dio: ^5.1.2
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.4.0
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.1.1
  get_it: ^7.6.0
  dartz: ^0.10.1
  shimmer: ^3.0.0
  go_router: ^7.1.1
  cupertino_icons: ^1.0.5
  video_player: ^2.6.1
  flutter_native_splash: any
  flutter_launcher_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1



flutter_native_splash:
  background_image: assets/images/splash.png

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/app_icon.png
  windows:
    generate: true
    image_path: assets/images/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/ar.json
    - assets/lang/en.json
  fonts:
   - family: main_font
     fonts:
       - asset: assets/fonts/Valorant Font.ttf